// Auto-generated by scripts/build_slides.py — do not edit by hand.
// Regenerate with: python3 scripts/build_slides.py

export type SlideDimensions = { readonly width: number; readonly height: number }

export const SLIDE_DIMENSIONS = {
  'cheek-fresh': { width: 4608, height: 3456 },
  'cheek-stained': { width: 4032, height: 3024 },
  'onion-fresh': { width: 2560, height: 1920 },
  'onion-stained': { width: 4284, height: 3985 },
} as const satisfies Record<string, SlideDimensions>
